apiVersion: v1
kind: Pod
metadata:
  name: meupod
spec:
  containers:
    - name: site
      image: fabricioveronez/web-page:blue
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: meusegundopod
  labels:
    app: meusegundopod
spec:
  containers:
    - name: site
      image: fabricioveronez/web-page:blue
      ports:
        - containerPort: 80
